// cubecloud-agent config center — P5 of the control-console plan
// (`docs/plans/2026-10-06-cubecloud-agent-integration-plan.md` §5.2 row
// "Config center + vault bridge") under the WRITTEN gate spec in
// `docs/plans/2026-10-06-workspace-agentic-os-coordination-matrix.md` §3.1.
//
// What this module does (single-writer, decided):
//   - Generates ONE artifact: the provision-time env fragment for the
//     workspace, with a hash-stamped header.
//   - `writeProvisionEnv(path, body)` is the only filesystem write — the
//     operator triggers it via the dedicated IPC; nothing here touches the
//     workspace's `config.yaml`, stores, or migrations (CI-banned).
//   - Any env change requires a supervised restart via the P1 supervisor —
//     this module never signals a live server (avoids the override-True
//     env bug class from the bring-up history).
//   - Secrets live in the desktop config/vault; logs carry fingerprints
//     only (`first4…last4`), never the key itself.
//
// Cubecloud original work (2026). Distributed under the repo's dual license
// per `LICENSE`; see `BRANDING_AND_LICENSE.md` for provenance.

import { promises as fs } from "fs";

export const PROVISION_STAMP_PREFIX = "# cubecloud-agent provision v1";

export interface ProvisionInput {
  /** The workspace origin (loopback http by row-A rules). */
  workspaceBaseUrl: string;
  /** Optional API key from the desktop vault (header auth provider). */
  workspaceApiKey?: string | null;
  /** Hermes gateway origin — voice upstream for the workspace proxy. */
  hermesBaseUrl?: string | null;
  /** Hermes gateway key from the vault (optional). */
  hermesApiKey?: string | null;
  /** Single-user local mode (M0/M1 attachment). */
  localSingleUser?: boolean;
  /** Extra operator-approved env lines (validated: KEY=VALUE only). */
  extraEnv?: Record<string, string>;
}

export interface ProvisionResult {
  env: string;
  /** 12-hex stamp of the body (reproducibility check for operators). */
  stamp: string;
}

async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  const bytes = new Uint8Array(digest);
  return Array.from(bytes.slice(0, 6))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Fingerprint an API key for logs/UI: first 4 + "…" + last 4. Anything
 *  shorter than 8 chars is "(set, short)"; empty is "(none)". */
export function fingerprintApiKey(key: string | null | undefined): string {
  if (!key) return "(none)";
  if (key.length < 8) return "(set, short)";
  return `${key.slice(0, 4)}…${key.slice(-4)}`;
}

function envLine(lines: string[], key: string, value: string | null | undefined): void {
  if (!value) return;
  lines.push(`${key}=${value}`);
}

/** Build the provision-time env fragment (pure — no I/O). */
export async function buildProvisionEnv(
  input: ProvisionInput,
): Promise<ProvisionResult> {
  const lines: string[] = [];
  const stampBody = `${PROVISION_STAMP_PREFIX}|${input.workspaceBaseUrl}`;

  envLine(lines, "CUBECLOUD_WORKSPACE_BASE_URL", input.workspaceBaseUrl);
  envLine(lines, "CUBECLOUD_WORKSPACE_API_KEY", input.workspaceApiKey || null);
  envLine(lines, "HERMES_VOICE_URL", input.hermesBaseUrl || null);
  envLine(lines, "HERMES_API_KEY", input.hermesApiKey || null);
  if (input.localSingleUser) {
    lines.push("OMNIGENT_LOCAL_SINGLE_USER=1");
  }
  for (const [key, value] of Object.entries(input.extraEnv ?? {})) {
    // Defensive: only plain KEY=VALUE pairs ride through.
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      envLine(lines, key, value);
    }
  }

  const body = lines.join("\n") + "\n";
  const stamp = (await sha256Hex(body + stampBody)).slice(0, 12);
  const header = `${PROVISION_STAMP_PREFIX} ${stamp} — generated by the Agentic OS console; changes require a supervised restart (omnigent server stop/start). Secrets in this file are fingerprints-logged only.`;
  return { env: `${header}\n\n${body}`, stamp };
}

/** The ONLY filesystem write this module performs — the provision
 *  fragment at an operator-chosen path (inside the workspace's provision
 *  location, per the gate spec). Returns the fingerprint for logging. */
export async function writeProvisionEnv(
  path: string,
  result: ProvisionResult,
): Promise<{ written: boolean; fingerprintedKeys: string[]; error: string | null }> {
  try {
    await fs.writeFile(path, result.env, "utf-8");
    // Log fingerprints only — the key material never reaches logs.
    const fingerprintedKeys: string[] = [];
    for (const line of result.env.split("\n")) {
      const match = line.match(/^([A-Z_]+)=(.+)$/);
      if (match && /API_KEY$/.test(match[1])) {
        fingerprintedKeys.push(`${match[1]}=${fingerprintApiKey(match[2])}`);
      }
    }
    return { written: true, fingerprintedKeys, error: null };
  } catch (err) {
    return { written: false, fingerprintedKeys: [], error: String(err) };
  }
}